name: Publish on PyPI

on:
  push:
    tags:
      - "v*"

jobs:

  build_wheel:
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install "setuptools>=67.2.0"
        pip install wheel build PyYAML
    - name: Build .whl
      run: |
        python -m build --wheel --skip-dependency-check
    - name: Archive wheels
      uses: actions/upload-artifact@v4
      with:
        name: pypi-wheels
        path: dist/*.whl

  build_source:
    name: Build source
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install "setuptools>=67.2.0"
        pip install wheel build PyYAML
    - name: Build .tar.gz
      run: |
        python -m build --sdist --skip-dependency-check
    - name: Archive wheels
      uses: actions/upload-artifact@v4
      with:
        name: pypi-source-dist
        path: dist/*.tar.gz

  publish_pypi:
    name: Publish 📦 on PyPI
    needs: [build_wheel, build_source]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
    - name: Collect and extract artifact
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: pypi-*
        merge-multiple: true
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
